apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "hytale-server.fullname" . }}-config
  labels:
    {{- include "hytale-server.labels" . | nindent 4 }}
data:
  JAVA_MEMORY: {{ .Values.server.memory | quote }}
  SERVER_PORT: {{ .Values.server.port | quote }}
  AUTH_MODE: {{ .Values.server.authMode | quote }}
  PATCHLINE: {{ .Values.server.patchline | quote }}
  ENABLE_BACKUP: {{ .Values.server.backup.enabled | quote }}
  BACKUP_FREQUENCY: {{ .Values.server.backup.frequency | quote }}
