{{- if not .Values.auth.existingSecret }}
{{- if or .Values.auth.sessionToken .Values.auth.identityToken }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hytale-server.fullname" . }}-auth
  labels:
    {{- include "hytale-server.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.auth.sessionToken }}
  session-token: {{ .Values.auth.sessionToken | b64enc | quote }}
  {{- end }}
  {{- if .Values.auth.identityToken }}
  identity-token: {{ .Values.auth.identityToken | b64enc | quote }}
  {{- end }}
{{- end }}
{{- end }}
