apiVersion: v1
kind: Service
metadata:
  name: {{ include "hytale-server.fullname" . }}
  labels:
    {{- include "hytale-server.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: hytale
      protocol: UDP
      name: hytale
      {{- if and (eq .Values.service.type "NodePort") .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
  selector:
    {{- include "hytale-server.selectorLabels" . | nindent 4 }}
