apiVersion: v2
name: hytale-server
description: A Helm chart for deploying Hytale dedicated game servers on Kubernetes
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - hytale
  - game-server
  - gaming
home: https://github.com/D4M13N-D3V/hytale-docker
sources:
  - https://github.com/D4M13N-D3V/hytale-docker
maintainers:
  - name: D4M13N-D3V
